version: '3.8'

services:
  app:
    build: ./bezkoder-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DATABASE_DEV="mongodb+srv://<username>:<password>@sem4.5y6rwjf.mongodb.net/<database>?retryWrites=true&w=majority"
      - DATABASE_PROD="mongodb+srv://<username>:<password>@sem4.5y6rwjf.mongodb.net/<database>?retryWrites=true&w=majority"
      - DATABASE_USERNAME="fullstackuser"
      - DATABASE_PASSWORD="ur8Jy2YVzdDXvJb"
      - DATABASE_NAME="fullstack"
      - JWT_SECRET="superdupersecrettokenauthentication"
      - PORT=3000

